version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "ams"
      POSTGRES_DB: "sysdb"
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
